eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8762
  servlet:
    context-path: ""

spring:
  application:
    name: service-hi

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

# http://localhost:8762/actuator/hystrix.stream
# http://localhost:8762/hystrix
